apiVersion: integration/v1
kind: Trigger
name: eventbridge-trigger
version: 1
summary: This is an eventbridge trigger for detecting events in AWS
description: |
  This is a generic trigger to receive any given payload from eventbridge.

responders:
- webhook

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/aws-eventbridge-trigger-eventbridge
