apiVersion: integration/v1
kind: Trigger
name: aws-eventbridge-trigger-eventbridge
version: 1
summary: This is an EventBridge trigger for detecting events in AWS
description: |
  This is a generic trigger to receive any given payload from EventBridge.

responders:
- webhook

schemas:
  event:
    source: file
    file: event.schema.json

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/aws-eventbridge-trigger-eventbridge

examples:
- summary: When an event is created
  content:
    apiVersion: v1
    kind: Trigger
    name: generic-webhook
    source:
      type: webhook
      image: relaysh/aws-eventbridge-trigger-eventbridge
    binding:
      parameters:
        data: !Data webhook_contents
